name: Node.js CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Node.js setup
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - run: npm ci
    - run: npm run build
    
    - name: Configure github stuff (Preparing to deploy)
      run: |
          git config user.name "Deployment AI"
          git config user.email "<>"
    - run: npm run deploy
    
