name: Node.js CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Node.js setup
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - run: npm ci
    - run: npm run build
    - run: git config --global user.email $(git log --pretty=format:"%ae" -n1)
    - run: git config --global user.name $(git log --pretty=format:"%an" -n1)
    - run: npm run deploy -- -e deploy
    
